name: Update pinned-gist
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  waka-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update waka-box
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 4af7ca54ef8dab96ea9dc10d6fab9527
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
